# Generated by Django 4.2.6 on 2023-10-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('number_records', models.PositiveSmallIntegerField()),
                ('collection_cost', models.FloatField()),
            ],
        ),
    ]
