# Generated by Django 4.2.6 on 2023-10-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_remove_record_info_collection_delete_enrollment'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.infocollection')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
        migrations.AddField(
            model_name='infocollection',
            name='record',
            field=models.ManyToManyField(related_name='records', through='info.CollectionRecord', to='record.record'),
        ),
    ]
