# Generated by Django 4.2.6 on 2023-10-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_collectionrecord_infocollection_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocollection',
            name='collection_cost',
        ),
    ]
