# Generated by Django 4.2.7 on 2023-11-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_infocollection_is_open_viewing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocollection',
            name='is_open_viewing',
            field=models.BooleanField(default=True),
        ),
    ]
