# Generated by Django 4.2.7 on 2023-11-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_infocollection_is_open_viewing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocollection',
            name='number_records',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
