# Generated by Django 4.2.7 on 2023-11-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_record_cover'),
        ('info', '0006_alter_infocollection_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocollection',
            name='record',
            field=models.ManyToManyField(related_name='records', through='info.CollectionRecord', to='record.record'),
        ),
    ]
