# Generated by Django 4.2.6 on 2023-10-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('realise_year', models.PositiveSmallIntegerField()),
                ('info_collection', models.ManyToManyField(to='info.infocollection')),
            ],
        ),
    ]
