# Generated by Django 4.2.6 on 2023-10-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='info_collection',
        ),
        migrations.AddField(
            model_name='record',
            name='info_collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collection_id', to='info.infocollection'),
        ),
    ]
