# Generated by Django 4.2.6 on 2023-10-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('record', '0002_remove_record_info_collection_record_info_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.infocollection')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
    ]
