# Generated by Django 4.2.6 on 2023-10-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('record', '0003_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='info_collection',
        ),
        migrations.AddField(
            model_name='record',
            name='info_collection',
            field=models.ManyToManyField(related_name='source_collection', through='record.Enrollment', to='info.infocollection'),
        ),
    ]
