# Generated by Django 4.2.6 on 2023-10-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_remove_record_info_collection_record_info_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='info_collection',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
