# Generated by Django 4.2.7 on 2023-11-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_remove_record_info_collection_delete_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='records/'),
        ),
    ]
